dist: trusty
language: rust
rust:
  # Don't forget to update in README and documentation.
  - 1.43.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add clippy rustfmt
script:
  - cargo test
  - cargo fmt
  - cargo clippy --bins --examples --tests --benches -- -D warnings
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - auto
