dist: trusty
language: rust
rust:
  # Don't forget to update in README and documentation.
  - 1.31.1
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy rustfmt
script:
  - cargo test
  - cargo fmt
  - cargo clippy --bins --examples --tests --benches -- -D warnings
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - auto
